name: publish

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Package app for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run package:lin

      - name: Package app for MacOS
        if: matrix.os == 'macos-latest'
        run: npm run package:mac

      - name: Package app for Windows
        if: matrix.os == 'windows-latest'
        run: npm run package:win

      - name: Release on Github
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
